name: flutter_app_lock
description: A Flutter package for shwoing a lock screen on app open and app pause.
version: 1.2.0
author: Tom Alabaster <tomalabasteruk@gmail.com>
homepage: https://github.com/tomalabaster/flutter_app_lock

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ^1.12.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
